import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center>
        <div>Hello , this is a demo how to use next js</div>
        <div>
          <Link href={"/posts"}>
            <a>Navigate to api fetching server side rendering demo</a>
          </Link>
        </div>

        <div>
          <Link href={"/users"}>
            <a>Navigate to api fetching static generated demo</a>
          </Link>
        </div>
      </Center>
    </div>
  );
}

const Center = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
`;
